services:
  app:
    build: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./config
          target: /app/config
        - action: sync+restart
          path: ./frontend
          target: /app/frontend
        - action: rebuild
          path: package.json
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/coreretrieve
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./frontend/documents:/app/frontend/documents

  db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=coreretrieve
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d coreretrieve"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
